projects:
  myapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql1/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql1
